addons:
  # modules to install before running tests
  include:
    - contacts
    # "contacts" already has mail in dependencies,
    # but without the following line DINAR may run odoo odoo with --init=mail,....
    # which leads to error on loading mail's demo data
    - mail

  # modules to exclude from installation/testing
  exclude:
    - hw_proxy

  server_wide_modules:
    - web

repo_readme:
  addons:
    - mail_to
    - mail_multi_website
